version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: Build docker image
          command: make build-docker-image

      - run:
          name: Verifying coding style
          command: make code-check

      - run:
          name: Running resinos tests
          command: make
